import { IBaseExt, IPaginationResponse, IOmitCreate, IOmitUpdate, IPickSearch, ICredential, IBasePagination, IResult, ISoftDelete } from "../models"
import { AxiosResponseWrapper } from '../lib/axios/typeHelper'
import { API_VERSION } from "../data/constant";
import axiosInstance from "../lib/axios";
export namespace Service {
    export type IUpdateService<TObj> = IOmitUpdate<TObj> & { id: string }
    // weakly typed
    export interface ICrud<TObj extends IBaseExt> {
        Search(_params: IPickSearch<TObj>): AxiosResponseWrapper<IPaginationResponse<TObj[]>>
        Get(_id: string): AxiosResponseWrapper<IResult<TObj>>
        Create(_data: IOmitCreate<TObj>): AxiosResponseWrapper
        Delete(_id: ISoftDelete): AxiosResponseWrapper
        Restore(_id: string): AxiosResponseWrapper
        Update(_params: IOmitUpdate<TObj>): AxiosResponseWrapper
    }

    export const apiEndpoints = {
        dichvus: "dichvus",
        hosonhaps: "hosonhaps",
        kenhtins: "kenhtins",
        loaidichvus: "loaidichvus",
        tokens: "tokens",
        tinbais: "tinbais",
        cocautochucs: "groups",
        cauhinhhethongs: "cauhinhhethongs",
        linhvucs: "linhvucs",
        mauphois: "mauphois",
        soLieuBaoCaos: "soLieuBaoCaos",
        LoaiGiayToKhoLuuTrus: "LoaiGiayToKhoLuuTrus",
        tailieucongdans: "tailieucongdans",
        thutucthietyeus: "thutucthietyeus",
        apichiases: "apichiases",
        khotailieudientus: "khotailieudientus",
        giaytosohoachiases: "giaytosohoachiases",
        phienbangiaytosohoakhotailieudientus: "phienbangiaytosohoakhotailieudientus",
        chukysocanhans: "chukysocanhans",
        logauthens: "logauthens",
        thutucs: "thutucs",
        danhmucchungs: "danhmucchungs",
        ngaynghis: "ngaynghis",
        loaiphilephis: "loaiphilephis",
        philephis: "philephis",
        donvithutucs: 'donvithutucs',
        quytrinhxulys: "quytrinhxulys",
        trangthaihosos: "trangthaihosos",
        nhomnguoidungs: "nhomnguoidungs",
        truonghopthutucs: "truonghopthutucs",
        kieunoidungs: "kieunoidungs",
        danhmucngays: "danhmucngays",
        buocxulys: 'buocxulys',
        thongbaos: 'thongbaos',
        diabans: 'diabans',
        users: "users",
        "personals/changepassword": "personals/changepassword",
        roles: "roles",
        "auth/profile": "auth/profile",
        groups: "groups",
        menus: "menus",
        "personal/profile": "personal/profile",
        hosos: "hosos",
        actions: "actions",
        screens: "screens",
        screenactions: "screenactions",
        thanhphanthutucs: "thanhphanthutucs",
        nguoidungnhomnguoidungs: "nguoidungnhomnguoidungs",
        configs: "configs",
        thanhphanhosos: "thanhphanhosos",
        giaytosohoas: "giaytosohoas",
        giaytohosos: "giaytohosos",
        quatrinhxulyhosos: "quatrinhxulyhosos",
        banners: 'banners',
        footers: 'footers',
        yeucauthanhtoans: "yeucauthanhtoans",
        trangthais: 'trangthais',
        hoidaps: 'hoidaps',
        phanAnhKienNghis: 'phanAnhKienNghis',
        huongdansudungs: 'huongdansudungs',
        hosobosungs: 'hosobosungs',
        taikhoanthuhuongs: 'taikhoanthuhuongs',
        quanlylienkets: 'quanlylienkets',
        giaodichthanhtoans: 'giaodichthanhtoans',
        thongkehosotructuyens: 'thongkehosotructuyens',
        quyetdinhs: 'quyetdinhs',
        thongkeportals: 'thongkeportals',
        baocaotonghops: "baocaotonghops",
        danhgiahailongs: "danhgiahailongs",
        userroles: "userroles",
        logtaikhoancsdldancudoanhnghieps: 'logtaikhoancsdldancudoanhnghieps',
        neacs: "neacs",
        adminhosos: "adminhosos",
        files: "files",
        ketqualienquans: "ketqualienquans",
        ketquathutucs: "ketquathutucs",
        quatrinhtraodoicongdans: "quatrinhtraodoicongdans",
        cauhoiphobiens: "cauhoiphobiens",
        dstailieuhdsds: 'dstailieuhdsds',
        menuketquathutucs: "menuketquathutucs",
        quanlyvanbans: 'quanlyvanbans',
        thaydoimucdothutucs: 'thaydoimucdothutucs',
        sochungthucs: 'sochungthucs',
        phieukhaosats: 'phieukhaosats',
        duthaoxulyhosos: "duthaoxulyhosos",
        danhmucgiaytochungthucs: "danhmucgiaytochungthucs",
        danhgiacoquans: "danhgiacoquans",
        dinhdanhcongdans: "dinhdanhcongdans",
        exportthongkes: "exportthongkes",
        thongKeKhoTaiLieuDienTus: "thongKeKhoTaiLieuDienTus",
        logthongkedghlcongdans: 'logthongkedghlcongdans',
        huongdannophosos: 'huongdannophosos',
        quanlytainguyens: "quanlytainguyens",
        logdeletedusers: "logdeletedusers",
        procgroup_mgrs: "nhomthutucs",
        typeofproc_mgrs: "loaithutucs",
        procofthistype_mgrs: "thutucthuocloais",
        assor_proc_mgrs: "thutuclienquans",
        tracuuthongtindoanhnghieps: "tracuuthongtindoanhnghieps",
        tracuuhokinhdoanhs: "tracuuhokinhdoanhs",
        tracuuhoptacxas: "tracuuhoptacxas",
        service_logs_mgrs: "logsendemails",
        vbdliss: "vbdliss",
        loainhomgiaytocanhans: "loainhomgiaytocanhans",
        tailieugiaytocanhans: "tailieugiaytocanhans",
    } as const
    export const primaryRoutes = {
        redirectUser: "/redirect-user",
        login: "/login",
        admin: {
            root: "/admin",

            dinhdanhcongdan: {
                root: "/admin/dinh-danh-cong-dan",
                chuaDinhDanh: "/admin/dinh-danh-cong-dan/tai-khoan-chua-dinh-danh",
                daDinhDanh: "/admin/dinh-danh-cong-dan/tai-khoan-da-dinh-danh",
                thongKeTrenCongDVC: "/admin/dinh-danh-cong-dan/thong-ke-tren-cong-dvc-tinh",
            },
            quanLyTruyCapDvc: {
                root: "/admin/truy-cap-dvc",
                quanLyTruyCapDvc: "/admin/truy-cap-dvc/quan-ly-truy-cap-dvc",
            },
            quanLyLienThongQLVB: {
                root: "/admin/lien-thong-qlvb",
                quanLyHoSo: "/admin/lien-thong-qlvb/quan-ly-ho-so",
                quanLyVanBan: "/admin/lien-thong-qlvb/quan-ly-van-ban",
            },
            quanLySuDungAPI: {
                root: "/admin/quan-ly-su-dung-api",
            },
            quanLySuDungKhoTaiLieuCaNhan: {
                root: "/admin/quan-ly-su-dung-kho-tai-lieu-ca-nhan",
                thongKeSuDung: "/admin/quan-ly-kho-tai-lieu-ca-nhan/thong-ke-su-dung",
                thongKeDungLuong: "/admin/quan-ly-kho-tai-lieu-ca-nhan/thong-ke-dung-luong",
            },
            dongBoKhoDienTuCongDan: {
                root: "/admin/dong-bo-kho-dien-tu-cong-dan",
                dvcqg: "/admin/dong-bo-kho-dien-tu-cong-dan/dvcqg",
                caNhan: "/admin/dong-bo-kho-dien-tu-cong-dan/ca-nhan",
                thongKeHeThong: "/admin/dong-bo-kho-dien-tu-cong-dan/thong-ke-he-thong",
                thongKeCaNhan: "/admin/dong-bo-kho-dien-tu-cong-dan/thong-ke-ca-nhan",
                dvctinh: "/admin/dong-bo-kho-dien-tu-cong-dan/dvc-tinh",
            },
            caNhanHoaNguoiDung: {
                root: "/admin/ca-nhan-hoa-nguoi-dung",
            },
            thongke: {
                root: "/admin/quan-tri-thong-ke",
                danhGiaHaiLong: "/admin/quan-tri-thong-ke/danh-gia-muc-do-hai-long",
                dashboardlienthongdvc: "/admin/quan-tri-thong-ke/thong-ke-dashboard",
                logdeleteduser: "/admin/quan-tri-thong-ke/danh-sach-thong-tin-nguoi-dung-bi-xoa"

            },
            quanTriNguoiDung: {
                root: "/admin/quan-tri-nguoi-dung",
                coCauToChuc: "/admin/quan-tri-nguoi-dung/co-cau-to-chuc",
                vaiTro: "/admin/quan-tri-nguoi-dung/vai-tro",
                nguoiDungDonVi: '/admin/quan-tri-nguoi-dung/nguoi-dung-don-vi',
                taiKhoanTuCSDLDanCu: '/admin/quan-tri-nguoi-dung/tk-csdl-dan-cu',
                doimatkhau: '/admin/quan-tri-nguoi-dung/doi-mat-khau',
                chuyendulieutaikhoan: '/admin/quan-tri-nguoi-dung/chuyen-du-lieu-tai-khoan',
                thongtintaikhoan: '/admin/quan-tri-nguoi-dung/thong-tin-tai-khoan',
                danhsachnguoidung: '/admin/quan-tri-nguoi-dung/danh-sach-nguoi-dung',
                listuserbypermission: '/admin/quan-tri-nguoi-dung/danh-sach-nguoi-dung-theo-quyen',

            },
            danhMucDungChung: {
                root: "/admin/danh-muc-dung-chung",
                danhMuc: "/admin/danh-muc-dung-chung/danh-muc",
                danhMucNgayNghi: "/admin/danh-muc-dung-chung/ngay-nghi",
                danhMucDiaBan: "/admin/danh-muc-dung-chung/dia-ban",
                loaiGiayToKhoLuuTru: "/admin/danh-muc-dung-chung/loai-giay-to-kho-luu-tru",

            },
            quanTriAPI: {
                root: "/admin/quan-ly-api",
                danhMuc: "/admin/quan-ly-api/api",
            },
            danhMucDVC: {
                root: "/admin/danh-muc-dvc",
                linhvuc: "/admin/danh-muc-dvc/linh-vuc",
                danhmucgiaytochungthuc: "/admin/danh-muc-dvc/giay-to-chung-thuc",
                thutuc: "/admin/danh-muc-dvc/thu-tuc",
                thuTucThietYeu: "/admin/danh-muc-dvc/thu-tuc-thiet-yeu",
                thutuccanbomotcua: "/admin/danh-muc-dvc/thu-tuc-can-bo-mot-cua",
                mauphoi: "/admin/danh-muc-dvc/mau-phoi",
                philephi: "/admin/danh-muc-dvc/phi-lephi",
                trangthai: "/admin/danh-muc-dvc/trang-thai",
                nhomnguoidung: "/admin/danh-muc-dvc/nhom-nguoi-dung",
                buocxuly: "/admin/danh-muc-dvc/buoc-xu-ly",
                donvi: "/admin/danh-muc-dvc/don-vi",
                thongbao: "/admin/danh-muc-dvc/thong-bao",
                taikhoanthuhuong: "/admin/danh-muc-dvc/tai-khoan-thu-huong",
                thuTucDonVis: "/admin/danh-muc-dvc/thu-tuc-don-vi",
                quanlydanhmucnganh: "/admin/danh-muc-dvc/quanlydanhmucnganh",
                thaydoimucdothutuc: "/admin/danh-muc-dvc/thay-doi-muc-do-thu-tuc",
                sochungthuc: "/admin/danh-muc-dvc/so-chung-thuc",
                logcsdldancudoannghiep: "/admin/danh-muc-dvc/csdl-dan-cu",
                procgroup_mgr: "/admin/danh-muc-dvc/procedure-group-management",
                assoc_proc_mgr: "/admin/danh-muc-dvc/assoc-proc-mgr",
                service_logs_mgr: "/admin/danh-muc-dvc/service-logs-mgr",
                bieuMauKetQuaDienTuTTHC: "/admin/danh-muc-dvc/bieu-mau-ket-qua-dien-tu-tthc",
                giayToDienTuTTHC: "/admin/danh-muc-dvc/giay-to-dien-tu-tthc",
            },
            quanTri: {
                root: "/admin/quan-tri",
                manager: "/admin/quan-tri/manager-procedure-menu",
                danhSachMenu: "/admin/quan-tri/danh-sach-menu",
                action: "/admin/quan-tri/action",
                screen: "/admin/quan-tri/screen",
                config: "/admin/quan-tri/config",
                quanLyTaiNguyen: "/admin/quan-tri/quan-ly-tai-nguyen",
                giaodichthanhtoan: "/admin/quan-tri/giao-dich-thanh-toan"
            },
            quanTriDonVi: {
                root: "/admin/quan-tri-don-vi",
                danhMucCoCauToChuc: "/admin/quan-tri-don-vi/danh-muc-co-cau-to-chuc",
                thuTuc: "/admin/quan-tri-don-vi/danh-muc-thu-tuc",
                danhMucNguoiDung: "/admin/quan-tri-don-vi/danh-muc-nguoi-dung",
                hoSoTheoDonVi: "/admin/quan-tri-don-vi/ho-so-theo-don-vi",
                sochungthuc: "/admin/quan-tri-don-vi/so-chung-thuc",
                nhomnguoidung: "/admin/quan-tri-don-vi/nhom-nguoi-dung-don-vi",
                thongkedghlcongdan: "/admin/quan-tri-don-vi/thong-ke-dghl-cong-dan",
                thongkedghlcanbo: "/admin/quan-tri-don-vi/thong-ke-dghl-can-bo",
                giaodichthanhtoan: "/admin/quan-tri-don-vi/giao-dich-thanh-toan"

            }
        },
        dvc: {
            root: "/dvc",
            dstailieuhdsdchocanbo: {
                root: "/dvc/dstailieuhdsdchocanbo",
            },
            danhgiahailong: {
                root: "/dvc/danh-gia-hai-long",
                danhGiaCoQuan: "/dvc/danh-gia-hai-long/danh-gia-co-quan",
                thongkedghl: "/dvc/danh-gia-hai-long/thong-ke-muc-do-hai-long",
                baoCao01: "/dvc/danh-gia-hai-long/bao-cao-mau01",
                baoCao02: "/dvc/danh-gia-hai-long/bao-cao-mau02",
                baoCao03: "/dvc/danh-gia-hai-long/bao-cao-mau03",
            },
            tiepNhanHoSo: {
                root: "/dvc/tiep-nhan-ho-so",
                moiTiepNhan: "/dvc/tiep-nhan-ho-so/moi-tiep-nhan",
                choTiepNhanTrucTuyen: "/dvc/tiep-nhan-ho-so/cho-tiep-nhan-truc-tuyen",
                tuChoiTiepNhan: "/dvc/tiep-nhan-ho-so/tu-choi-tiep-nhan",
                daChuyenXuLy: "/dvc/tiep-nhan-ho-so/da-chuyen-xu-ly",
            },
            soHoaHoSo: {
                root: "/dvc/so-hoa-ho-so",
                choDuyet: "/dvc/so-hoa-ho-so/cho-duyet",
                daDuyet: "/dvc/so-hoa-ho-so/da-duyet",
                khongDuyet: "/dvc/so-hoa-ho-so/khong-duyet",
                toanBo: "/dvc/so-hoa-ho-so/toan-bo",
            },
            xuLyHoSo: {
                root: "/dvc/xu-ly-ho-so",
                dangXuLy: "/dvc/xu-ly-ho-so/dang-xu-ly",
                dangXuLyLienThong: "/dvc/xu-ly-ho-so/dang-xu-ly-lien-thong",
                vpubDangXuLy: "/dvc/xu-ly-ho-so/vpub/dang-xu-ly",
                dungXuLy: "/dvc/xu-ly-ho-so/dung-xu-ly",
                yeuCauThucHienNghiaVuTaiChinh: "/dvc/xu-ly-ho-so/yeu-cau-thuc-hien-nghia-vu-tai-chinh",
                daChuyenXuLy: "/dvc/xu-ly-ho-so/da-chuyen-xu-ly",
                daChuyenCoKetQua: "/dvc/xu-ly-ho-so/da-chuyen-co-ket-qua",
                daChuyenBoSung: "/dvc/xu-ly-ho-so/da-chuyen-bo-sung",
            },
            traKetQua: {
                root: "/dvc/tra-ket-qua",
                choTraTrucTuyen: "/dvc/tra-ket-qua/cho-tra-truc-tuyen",
                choTraTrucTiep: "/dvc/tra-ket-qua/cho-tra-truc-tiep",
                choTraBCCI: "/dvc/tra-ket-qua/cho-tra-bcci",
                choTraBCCITheoNguoiTiepNhan: "/dvc/tra-ket-qua/nguoi-tiep-nhan-cho-tra-bcci",

                choTraBCCITTHCC: "/dvc/tra-ket-qua/cho-tra-bcci-tthcc",
                choTraKetQua: "/dvc/tra-ket-qua/cho-tra-ket-qua",
                choTraKetQuaTTHCC: "/dvc/tra-ket-qua/cho-tra-ket-qua-tthcc",
                choTraKetQuaTheoNguoiTiepNhan: "/dvc/tra-ket-qua/nguoi-tiep-nhan-cho-tra-ket-qua",
                xinRut: "/dvc/tra-ket-qua/xin-rut",
                daTra: "/dvc/tra-ket-qua/da-tra",
                daTraTTHCC: "/dvc/tra-ket-qua/da-tra-tthcc",
                daTraKetQuaTheoNguoiTiepNhan: "/dvc/tra-ket-qua/nguoi-tiep-nhan-da-tra-ket-qua",
                choXacNhanTraKq: "/dvc/tra-ket-qua/cho-xac-nhan-tra-kq",
                choXacNhanTraKqChuaThuPhi: "/dvc/tra-ket-qua/cho-xac-nhan-chua-thu-phi",
                daCoKetQua: "/dvc/tra-ket-qua/da-co-ket-qua",
                theoDoiChuyenTraKq: "/dvc/tra-ket-qua/theo-doi-da-chuyen-tra-kq",
            },
            boSungHoSo: {
                root: "/dvc/bo-sung-ho-so",
                yeuCauBoSung: "/dvc/bo-sung-ho-so/yeu-cau-bo-sung",
                choBoSung: "/dvc/bo-sung-ho-so/cho-bo-sung",
                daBoSung: "/dvc/bo-sung-ho-so/da-bo-sung",
                daHoanThanhBoSung: "/dvc/bo-sung-ho-so/da-hoan-thanh-bo-sung",
            },
            huongDanNopHoSo: {
                root: "/dvc/huong-dan-nop-ho-so",
                danhSachHuongDanNopHoSo: "/dvc/huong-dan-nop-ho-so/danh-sach-huong-dan",

            },
            quanLyTaiNguyen: {
                root: "/dvc/quan-ly-tai-nguyen"
            },
            theoDoiHoSo: {
                root: "/dvc/theo-doi-ho-so",
                hoSoToiHan: "/dvc/theo-doi-ho-so/ho-so-toi-han",
                hoSoQuaHan: "/dvc/theo-doi-ho-so/ho-so-qua-han",
                theoDoiTatCaHoSo: "/dvc/theo-doi-ho-so/theo-doi-tat-ca-ho-so",
                theoDoiTrangThaiXuLyHoSo: "/dvc/theo-doi-ho-so/trang-thai-xu-ly-ho-so",
                theoDoiHoSoKhongDuocTiepNhan: "/dvc/theo-doi-ho-so/khong-duoc-tiep-nhan",
            },
            theoDoiHoSoTN: {
                root: "/dvc/theo-doi-ho-so-tn",
                hoSoToiHan: "/dvc/theo-doi-ho-so-tn/ho-so-toi-han",
                hoSoQuaHan: "/dvc/theo-doi-ho-so-tn/ho-so-qua-han",
                theoDoiTatCaHoSo: "/dvc/theo-doi-ho-so-tn/theo-doi-tat-ca-ho-so",
            },
            thuPhiLePhi: {
                root: "/dvc/thu-phi-le-phi",
                choThuPhi: "/dvc/thu-phi-le-phi/cho-thu-phi",
                daThuPhi: "/dvc/thu-phi-le-phi/da-thu-phi",
                daHoanPhi: "/dvc/thu-phi-le-phi/da-hoan-phi",
                huyThuPhi: "/dvc/thu-phi-le-phi/huy-thu-phi",
                theoDoiHuyThuPhi: "/dvc/thu-phi-le-phi/theo-doi-huy-thu-phi",
                theoDoiChoThuPhi: "/dvc/thu-phi-le-phi/theo-doi-cho-thu-phi",
                theoDoiDaHoanPhi: "/dvc/thu-phi-le-phi/theo-doi-da-hoan-phi",
                theoDoiDaThuPhi: "/dvc/thu-phi-le-phi/theo-doi-da-thu-phi",
                hoSoDaThuPhiTrucTruyen: "/dvc/thu-phi-le-phi/ho-so-da-thu-phi-truc-tuyen",
                tinhHinhSuDungBienLaiThuPhiLePhi: "/dvc/thu-phi-le-phi/tinh-hinh-su-dung-bien-lai-thu-phi-le-phi",
                thongKeThuPhiLePhi: "/dvc/thu-phi-le-phi/thong-ke-thu-phi-le-phi",
            },
            traCuu: {
                root: "/dvc/tra-cuu",
                csdlDanCu: "/dvc/tra-cuu/csdl-dan-cu",
                tatCaHoSo: "/dvc/tra-cuu/tat-ca-ho-so",
                hoSoDienTu: "/dvc/tra-cuu/ho-so-dien-tu",
                scanHoSoDienTu: "/dvc/tra-cuu/scan-ho-so-dien-tu",
                scanHoSoDienTuChuaScanKetQua: "/dvc/tra-cuu/scan-ho-so-dien-tu-chua-scan-ket-qua",
                scanHoSoDienTuDaScanKetQua: "/dvc/tra-cuu/scan-ho-so-dien-tu-da-scan-ket-qua",
                kySoHoSoDienTu: "/dvc/tra-cuu/ky-so-ho-so-dien-tu",
                daKySoHoSoDienTu: "/dvc/tra-cuu/da-ky-so-ho-so-dien-tu",
                chuaKySoHoSoDienTu: "/dvc/tra-cuu/chua-ky-so-ho-so-dien-tu",
                hoSoChoCanBoTraKQ: "/dvc/tra-cuu/ho-so-cho-can-bo-tra-ket-qua",
                hoSoTheoDonVi: "/dvc/tra-cuu/ho-so-theo-don-vi",
                adminYeuCauThanhToan: "/dvc/tra-cuu/admin-yeu-cau-thanh-toan",
                hoSoLienThong: "/dvc/tra-cuu/ho-so-lien-thong",
                hoSoTraLaiXinRut: "/dvc/tra-cuu/ho-so-tra-lai-xin-rut",
                hoSoChoBoSung: "/dvc/tra-cuu/ho-so-cho-bo-sung",
                hoSoThuocDoiTuongMienPhi: "/dvc/tra-cuu/ho-so-thuoc-doi-tuong-mien-phi",
                thongTinDoanhNghiep: "/dvc/tra-cuu/thong-tin-doanh-nghiep",
                hoKinhDoanh: "/dvc/tra-cuu/ho-kinh-doanh",
                thongtinTab: "/dvc/tra-cuu/tra-cuu-thong-tin"
            },
            hoSoSoHoa: {
                chuaSoHoa: "/dvc/ho-so-so-hoa/ho-so-chua-so-hoa",
                daSoHoa: "/dvc/ho-so-so-hoa/ho-so-da-so-hoa"
            },
            canBoBCCI: {
                root: "/dvc/bcci",
                dangKy: "/dvc/bcci/dang-ky",
                daDangKy: "/dvc/bcci/da-dang-ky",
                daTraKetQua: "/dvc/bcci/da-tra-kq",
                congDanDaDangKy: "/dvc/bcci/cong-dan-dang-ky-nhan-kq-qua-bcci",
                thongketiepnhanhosovatrakq: "/dvc/bcci/thong-ke-tiep-nhan-ho-so-va-tra-ket-qua-bcci",
                thongKeHoSoDangKyNhanKqQuaBCCI: "/dvc/bcci/thong-ke-dang-ky-nhan-kq-qua-bcci"
            },
            thongKe: {
                root: "/dvc/thong-ke",
                hoSoLienThong: "/dvc/thong-ke/thong-ke-ho-so-lien-thong",
                hoSoTrongNgay: "/dvc/thong-ke/thong-ke-ho-so-trong-ngay",
                tiepNhanHoSoTrucTuyen: {
                    root: "/dvc/thong-ke/tiep-nhan-ho-so-truc-tuyen",
                    tiepNhanHoSoTrucTuyenCapTinh: "/dvc/thong-ke/ho-so-truc-tuyen-cap-tinh",
                    tiepNhanHoSoTrucTuyenCacSoBanNganh: "/dvc/thong-ke/ho-so-truc-tuyen-cac-so-ban-nganh",
                    tiepNhanHoSoTrucTuyenCapHuyen: "/dvc/thong-ke/ho-so-truc-tuyen-cap-huyen",
                    tiepNhanHoSoTrucTuyen: "/dvc/thong-ke/ho-so-truc-tuyen",
                    tiepNhanHoSoTrucTuyenCapXa: "/dvc/thong-ke/ho-so-truc-tuyen-cap-xa",
                    thongKeHoSoTrucTuyenTheoThuTuc: "/dvc/thong-ke/ho-so-truc-tuyen-theo-thu-tuc",
                    hoSoTiepNhanQuaHan: "/dvc/thong-ke/ho-so-tiep-nhan-qua-han",
                    theoMucDo34: "/dvc/thong-ke/ho-so-truc-tuyen-theo-muc-do-34",
                },
                tongHop: {
                    thongKeDanhSachThuTuc: "/dvc/thong-ke/danh-sach-thu-tuc",
                    thongKeDanhSachHoSo: "/dvc/thong-ke/danh-sach-ho-so",
                    thongKeTheoTrangThaiHoSo: "/dvc/thong-ke/thong-ke-theo-trang-thai-ho-so"
                },
                thuPhiLePhi: {
                    theoHinhThucThanhToan: "/dvc/thong-ke/thanh-toan-theo-hinh-thuc-thanh-toan",
                    theoHinhThucThanhToanDonVi: "/dvc/thong-ke/thanh-toan-theo-hinh-thuc-thanh-toan-don-vi",
                },
                quyetDinh766: {
                    root: "/dvc/thong-ke/quyet-dinh-766",
                    tienDoGiaiQuyet: "/dvc/thong-ke/tien-do-giai-quyet",
                    theoDoiChiTieuDVCTrucTuyen: "/dvc/thong-ke/theo-doi-chi-tieu-dvc-truc-tuyen",
                    traCuuCSDLDanCu: "/dvc/thong-ke/bao-cao-so-luong-tra-cuu-csdl-dan-cu",
                    thanhToanTrucTuyen: "/dvc/thong-ke/thanh-toan-truc-tuyen",
                    thongKeTongHop: "/dvc/thong-ke/thong-ke-tong-hop",
                    thongKeTongHopThuTuc: "/dvc/thong-ke/tong-hop-thu-tuc",
                    baoCaoTheoThuTuc: "/dvc/thong-ke/bao-cao-theo-thu-tuc",
                    BaoCaoTongHopThuTucTheoDonVi: "/dvc/thong-ke/tong-hop-thu-tuc-theo-don-vi",
                    baoCaoTheoLinhVuc: "/dvc/thong-ke/bao-cao-theo-linh-vuc",
                    baoCaoTheoLinhVuc2: "/dvc/thong-ke/bao-cao-theo-linh-vuc-2",
                    baoCaoDonViLinhVuc: "/dvc/thong-ke/bao-cao-don-vi-linh-vuc",
                    baoCaoTheoDonVi: "/dvc/thong-ke/bao-cao-tong-hop-don-vi",
                    baoCaoTheoDonVi2: "/dvc/thong-ke/bao-cao-tong-hop-don-vi-2",
                    baoCaoTheoTruongHop: "/dvc/thong-ke/bao-cao-tong-hop-theo-truong-hop",
                    baoCaoHoSoNopTuCongDVC: "/dvc/thong-ke/bao-cao-ho-so-nop-tu-dvc",
                    baoCao06a: "/dvc/thong-ke/bao-cao-06a",
                    baoCao07b: "/dvc/thong-ke/bao-cao-07b",
                    baoCao06CacCap: "/dvc/thong-ke/bao-cao-06-cac-cap",

                    baoCao07a: "/dvc/thong-ke/bao-cao-07a",
                    thanhToanTrucTuyen2: "/dvc/thong-ke/thanh-toan-truc-tuyen-2",
                    theoDoiChiTieuDVCTrucTuyen2: "/dvc/thong-ke/theo-doi-chi-tieu-dvc-truc-tuyen-2",
                    tienDoGiaiQuyet2: "/dvc/thong-ke/tien-do-giai-quyet-2",
                    chiTieuSoHoa: "/dvc/thong-ke/chi-tieu-so-hoa",
                    hoSoQuaHan: "/dvc/thong-ke/ho-so-qua-han",
                    soTheoDoiHoSo: "/dvc/thong-ke/so-theo-doi-ho-so",
                    thongKeThanhToanTrucTuyen: "/dvc/thong-ke/thong-ke-thanh-toan-truc-tuyen",
                    donDocThanhToanTrucTuyen: "/dvc/thong-ke/don-doc-thanh-toan-truc-tuyen",
                    donDocThanhToanTrucTuyenDonVi: "/dvc/thong-ke/don-doc-thanh-toan-truc-tuyen-don-vi",
                    thongKeNguoiNopHoSo: "/dvc/thong-ke/nguoi-nop-ho-so",
                    tongHopThanhToanTheoDonVi: "/dvc/thong-ke/tong-hop-thanh-toan/don-vi",
                    thongKeThuTucPhatSinhHoSo: "/dvc/thong-ke/thu-tuc-phat-sinh-ho-so",
                    thongKeThuTucKhongPhatSinhHoSo: "/dvc/thong-ke/thu-tuc-khong-phat-sinh-ho-so",
                    thongKeSoLuongThuTucTheoDonVi: "/dvc/thong-ke/so-luong-thu-tuc-theo-don-vi",
                    tiepNhanHoSoTheoDonVi: "/dvc/thong-ke/tiep-nhan-ho-so-theo-don-vi"
                },
                hoSoChungThuc: {
                    root: "/dvc/thong-ke/ho-so-chung-thuc",
                }
            },
            chungThuc: {
                root: "/dvc/chung-thuc",
                moiTiepNhan: "/dvc/chung-thuc/tiep-nhan-ho-so",
                choTiepNhanTrucTuyen: "/dvc/chung-thuc/cho-tiep-nhan-truc-tuyen",
                dangXuLy: "/dvc/chung-thuc/dang-xu-ly",
                choTraKetQua: "/dvc/chung-thuc/cho-tra-ket-qua",
                daTraKetQua: "/dvc/chung-thuc/da-tra-ket-qua",
                danhMucSoChungThuc: "/dvc/chung-thuc/danh-muc-so-chung-thuc",
                theoDoiHoSoChungThuc: "/dvc/chung-thuc/theo-doi-ho-so-chung-thuc",
            },
            chamSoHoa: {
                root: "/dvc/cham-so-hoa",
                choSoHoa: "/dvc/cham-so-hoa/cho-so-hoa",
                daSoHoa: "/dvc/cham-so-hoa/da-so-hoa",
            },
            duThaoXuLyHoSo: {
                root: "/dvc/du-thao-xu-ly-ho-so",
                boSungChoXuLy: "/dvc/du-thao-xu-ly-ho-so/bo-sung-cho-xu-ly",
                traLaiXinRutChoXuLy: "/dvc/du-thao-xu-ly-ho-so/tra-lai-xin-rut-cho-xu-ly",
                boSungDaXuLy: "/dvc/du-thao-xu-ly-ho-so/bo-sung-da-xu-ly",
                traLaiXinRutDaXuLy: "/dvc/du-thao-xu-ly-ho-so/tra-lai-xin-rut-da-xu-ly",
                boSungChoDuyetThongQua: "/dvc/du-thao-xu-ly-ho-so/bo-sung-cho-duyet-thong-qua",
                traLaiXinRutChoDuyetThongQua: "/dvc/du-thao-xu-ly-ho-so/tra-lai-xin-rut-cho-duyet-thong-qua",
                xinLoiChoDuyetThongQua: "/dvc/du-thao-xu-ly-ho-so/xin-loi-cho-duyet-thong-qua",
                xinLoiDaXuLy: "/dvc/du-thao-xu-ly-ho-so/xin-loi-da-xu-ly",
            },
            hoSoPhiDiaGioi: {
                root: "/dvc/ho-so-phi-dia-gioi",
                tiepNhan: "/dvc/ho-so-phi-dia-gioi/tiep-nhan",
                dangXuLy: "/dvc/ho-so-phi-dia-gioi/dang-xu-ly",
                tuChoi: "/dvc/ho-so-phi-dia-gioi/tu-choi",
                boSung: "/dvc/ho-so-phi-dia-gioi/bo-sung",
                choTra: "/dvc/ho-so-phi-dia-gioi/cho-tra",
                daTra: "/dvc/ho-so-phi-dia-gioi/da-tra",
                traCuu: "/dvc/ho-so-phi-dia-gioi/tra-cuu",
                choKyDuyet: "/dvc/ho-so-phi-dia-gioi/cho-ky-duyet",
                thongKe: "/dvc/ho-so-phi-dia-gioi/thong-ke",
                choTiepNhan: "/dvc/ho-so-phi-dia-gioi/cho-tiep-nhan",
                daTiepNhan: "/dvc/ho-so-phi-dia-gioi/da-tiep-nhan",
                daChuyen: "/dvc/ho-so-phi-dia-gioi/da-chuyen",
            }

        },
        portaldvc_admin: {
            root: "/portaldvc_admin",
            banner: "/portaldvc_admin/banner",
            footer: "/portaldvc_admin/footer",
            kieunoidung: "/portaldvc_admin/kieunoidung",
            kenhtin: "/portaldvc_admin/kenhtin",
            trangthai: "/portaldvc_admin/trangthai",
            tinbai: "/portaldvc_admin/tinbai",
            quanlylienket: "/portaldvc_admin/quanlylienket",
            huongdansudung: "/portaldvc_admin/huongdansudung",
            cauhoiphobien: "/portaldvc_admin/cauhoiphobien",
            dstailieuhdsd: "/portaldvc_admin/dstailieuhdsd",
            dstailieuhdsdchocanbo: "/portaldvc_admin/dstailieuhdsdchocanbo",
            hoidap: "/portaldvc_admin/hoidap",
            paknChuaTraLoi: "/portaldvc_admin/pakn-cho-tra-loi",
            paknDaTraLoi: "/portaldvc_admin/pakn-da-tra-loi",
            quantrivanban: "/portaldvc_admin/quantrivanban",
            taoqrcode: "/portaldvc_admin/tao-qrcode",
            thongKeKhoTaiLieuDienTu: "/portaldvc_admin/thong-ke-kho-tai-lieu-dien-tu",

        },
        portaldvc: {
            root: '/portaldvc',
            hosocanhan: {
                root: "/portaldvc/ho-so-ca-nhan",
                dichVuCongCuaToi: '/portaldvc/ho-so-ca-nhan/dvc-dich-vu-cong-cua-toi',
                thanhToanPhiLePhi: '/portaldvc/ho-so-ca-nhan/dvc-thanh-toan-phi-le-phi',
                taiLieuDienTu: '/portaldvc/ho-so-ca-nhan/dvc-tai-lieu-dien-tu',
                thongTinDinhDanh: '/portaldvc/ho-so-ca-nhan/dvc-thong-tin-tai-khoan',
                hoSoLuuTru: '/portaldvc/ho-so-ca-nhan/dvc-ho-so-luu-tru',
                khoTaiLieuDienTu: '/portaldvc/ho-so-ca-nhan/dvc-kho-tai-lieu-dien-tu',
                chuKyDienTu: '/portaldvc/ho-so-ca-nhan/dvc-chu-ky-so-ca-nhan',
                taiLieuCongDan: '/portaldvc/ho-so-ca-nhan/kho-tai-lieu-ca-nhan',
                taiLieuCongDanNamDinh: '/portaldvc/ho-so-ca-nhan/nd-kho-tai-lieu-ca-nhan',
            },
            home: '/portaldvc/home',
            tinTuc: '/portaldvc/tin-tuc',
            kieunoidung: "/portaldvc_admin/kieunoidung",
            kenhtin: "/portaldvc_admin/kenhtin",
            dvcQuocGia: "/portaldvc/KenhTin/dich-vu-cong-nop-ho-so-dvc-quoc-gia",
            trangthai: "/portaldvc_admin/trangthai",
            // tinbai: "/portaldvc_admin/tinbai",
            // kieunoidung: "/portaldvc_admin/kieunoidung",
            // kenhtin: "/portaldvc_admin/kenhtin",
            // trangthai: "/portaldvc_admin/trangthai",
            tinbai: '/portaldvc/tin-bai/:id',
            hoidap: "/portaldvc/hoi-dap",
            hoidapchitiet: '/portaldvc/hoi-dap/:id',
            danhmucTTHC: "/portaldvc/danh-muc-tthc",
            guiPAKN: "/portaldvc/pakn-dvc-tinh",
            danhSachPAKN: "/portaldvc/danh-sach-pakn-dvc-tinh",
            chitietthutuc: '/portaldvc/chi-tiet-thu-tuc/:id',
            trangWiki: '/portaldvc/trang-tin/:id',
            traCuu: '/portaldvc/tra-cuu',
            traCuuBienLaiDienTu: '/portaldvc/tra-cuu-bien-lai-dien-tu',
            dvcTrucTuyen: '/portaldvc/dvc-truc-tuyen',
            thanhToan: '/portaldvc/thanh-toan',
            xacNhanThanhToan: '/portaldvc/thanh-toan/xac-nhan',
            nopHoSoTrucTuyen: '/portaldvc/nop-ho-so-truc-tuyen',
            huongdansudungportal: '/portaldvc/huong-dan-su-dung',
            nhungcauhoithuonggap: '/portaldvc/nhung-cau-hoi-thuong-gap',
            nhungcauhoithuonggapchitiet: '/portaldvc/nhung-cau-hoi-thuong-gap/:id',
            dstailieuhuongdansudung: '/portaldvc/danh-sach-tai-lieu-hdsd',
            quanlyvanban: '/portaldvc/quan-ly-van-ban',
            danhgiahailong: '/portaldvc/danh-gia-hai-long',
            lienhecaphuyenxa: '/portaldvc/lien-he-cap-huyen-xa',
            lienhecaptinh: '/portaldvc/lien-he-cap-tinh',
            thongke: "/portaldvc/thong-ke",
            thongkeMap: "/portaldvc/thong-ke-map",
            banDoTheChe: '/portaldvc/ban-do-the-che',


        },
        readQrCode: {
            root: '/apiqr/qr'
        },
        chiSoTienDoGiaiQuyet: {
            root: '/portaldvc/chi-so-tien-do-giai-quyet',
            // thongKeTongHopPortal: '/portaldvc/guest/thong-ke-hcc',
            // thongKeTongHopThangPortal: '/portaldvc/guest/thong-ke-thang-hcc',
            traCuuHccPortal: '/portaldvc/guest/tra-cuu-hcc',
            danhGiaHaiLongHcc: '/portaldvc/guest/danh-gia-hai-long-hcc',
        },
        smartkiosk: {
            root: '/smartkiosk'
        },
        mobile: {
            nopHoSoTrucTuyen: "/mobile/nop-ho-so-truc-tuyen",
            hoSoNhap: "/mobile/ho-so-nhap",
            chatBot: "/mobile/chat-bot",
        },
        admin_tthc: {
            root: "/admin_tthc",
        },
        file: {
            root: "/files"
        },
        filepublic: {
            root: "/portaldvc/filepublic"
        }



    }
    export type AppEndpoint = keyof typeof apiEndpoints
    export class BaseApi {
        public readonly _urlSuffix: string
        // public readonly _axios = axiosInstance 
        constructor(keyEndpoint: AppEndpoint, apiVersion: string = API_VERSION) {
            this._urlSuffix = apiVersion + apiEndpoints[keyEndpoint]
        }
    }
}
