import { IBaseExt, IOmitUpdate } from "@/models";

export interface IAdminYeuCauThanhToan extends IBaseExt {
    maHoSo? : string,
    ma? : string,
    soTien?: number,
    phi?: number,
    lePhi?: number,
    trangThai? : string,
    ngayYeuCau? : string,
    nguoiYeuCau? : string,
    donViThu? : string,
    hinhThucThanhToan? : string,
    hinhThucThu? : string,
    chiTiet? : string,
    ghiChuThanhToan? : string,
    mauSoBienLai? : string,
    kyHieuBienLai? : string,
    soHieuBienLai? : string,
    nguoiThuPhi? : string,
    ngayThuPhi? : string,
    donViThuPhiMaSoThue? : string,
    donViMaSoThue? : string,
    ngayHoanPhi? : string,
    nguoiHoanPhi? : string,
    lyDoHoanPhi? : string,
    ngayHuy? : string,
    nguoiHuy? : string,
    lyDoHuy? : string,
    donVi? : string,
}
export type AdminUpdateYeuCauThanhToanParams = IOmitUpdate<IAdminYeuCauThanhToan> ;