namespace TD.DichVuCongApi.Application.Business.YeuCauThanhToanApp;
public class YeuCauThanhToanDetailDto
{
    public DefaultIdType Id { get; set; }
    public DefaultIdType HoSoId { get; set; }
    public string MaHoSo { get; set; }
    public string Ma { get; set; }
    public int SoTien { get; set; }
    public int Phi { get; set; }
    public int LePhi { get; set; }
    public int PhiTheoTTHC { get; set; }
    public int LePhiTheoTTHC { get; set; }
    public string? TrangThai { get; set; }
    public DateTime? NgayYeuCau { get; set; }
    public string? NguoiYeuCau { get; set; }
    public string? TaiKhoanNguoiYeuCau { get; set; }
    public string? TenNguoiYeuCau { get; set; }
    public string? DonVi { get; set; }
    public string? DonViThu { get; set; }
    public string? TenDonViThu { get; set; }
    public string HinhThucThanhToan { get; set; }
    public string HinhThucThu { get; set; }
    public string? ChiTiet { get; set; }
    public string? GhiChuThanhToan { get; set; }
    public string? MauSoBienLai { get; set; }
    public string? KyHieuBienLai { get; set; }
    public string? NguoiThuPhi { get; set; }
    public DateTime? NgayThuPhi { get; set; }
    public string? DonViThuPhiMaSoThue { get; set; }
    public string? DonViMaSoThue { get; set; }
    public DateTime? NgayHoanPhi { get; set; }
    public string? NguoiHoanPhi { get; set; }
    public string? LyDoHoanPhi { get; set; }
    public DateTime? NgayHuy { get; set; }
    public string? NguoiHuy { get; set; }
    public string? LyDoHuy { get; set; }
    public string? ChuHoSo { get; set; }
    public string? DiaChiChuHoSo { get; set; }
    public string? SoGiayToChuHoSo { get; set; }
    public string? EmailChuHoSo { get; set; }
    public string? EmailNguoiNopTienBienLai { get; set; }
    public string? MaDonViThucHienHoSo { get; set; }
    public string? MaDinhDanh { get; set; }
    public string? TenDonViThucHienHoSo { get; set; }
    public string? MaTTHC { get; set; }
    public string? TenTTHC { get; set; }
    public string? TaiKhoanThuHuong { get; set; }
    public string? TenTaiKhoanThuHuong { get; set; }
    public string? MaNganHang { get; set; }
    public string? NguoiNopTienBienLai { get; set; }
    public string? MaSoThueBienLai { get; set; }
    public string? DiaChiBienLai { get; set; }
    public string? NguoiUyQuyen { get; set; }
    public string? SoDienThoaiNguoiUyQuyen { get; set; }
    public string? DiaChiNguoiUyQuyen { get; set; }
    public string? NoiDung { get; set; }
    public string? SoBienLai { get; set; }
    public string? TenPhiBienLai { get; set; }
    public string? TenLePhiBienLai { get; set; }
    public string? LoaiBienLaiThanhToan { get; set; }
    public string? LoaiDoiTuong { get; set; }
    public string? SoDienThoaiChuHoSo { get; set; }
    public string? SoDienThoaiNguoiNopTienBienLai { get; set; }
    public string? SoGiayToNguoiNopTienBienLai { get; set; }
    public string? TrichYeuHoSo { get; set; }
    public string? SoBienLaiPhi { get; set; }
    public string? SoBienLaiLePhi { get; set; }
    public DateTime? NgayLapHoaDonPhi { get; set; }
    public DateTime? NgayLapHoaDonLePhi { get; set; }
}
