//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VnptPublishService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VnptPublishService.PublishServiceSoap")]
    public interface PublishServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportAndPublishInv", ReplyAction="*")]
        System.Threading.Tasks.Task<VnptPublishService.ImportAndPublishInvResponse> ImportAndPublishInvAsync(VnptPublishService.ImportAndPublishInvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInv", ReplyAction="*")]
        System.Threading.Tasks.Task<VnptPublishService.ImportInvResponse> ImportInvAsync(VnptPublishService.ImportInvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInv", ReplyAction="*")]
        System.Threading.Tasks.Task<VnptPublishService.publishInvResponse> publishInvAsync(VnptPublishService.publishInvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInvByFkey", ReplyAction="*")]
        System.Threading.Tasks.Task<VnptPublishService.publishInvByFkeyResponse> publishInvByFkeyAsync(VnptPublishService.publishInvByFkeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCus", ReplyAction="*")]
        System.Threading.Tasks.Task<VnptPublishService.UpdateCusResponse> UpdateCusAsync(VnptPublishService.UpdateCusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCusCert", ReplyAction="*")]
        System.Threading.Tasks.Task<VnptPublishService.setCusCertResponse> setCusCertAsync(VnptPublishService.setCusCertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHashInvWithToken", ReplyAction="*")]
        System.Threading.Tasks.Task<VnptPublishService.getHashInvWithTokenResponse> getHashInvWithTokenAsync(VnptPublishService.getHashInvWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInvWithToken", ReplyAction="*")]
        System.Threading.Tasks.Task<VnptPublishService.publishInvWithTokenResponse> publishInvWithTokenAsync(VnptPublishService.publishInvWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPublish", ReplyAction="*")]
        System.Threading.Tasks.Task<VnptPublishService.getPublishResponse> getPublishAsync(VnptPublishService.getPublishRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportAndPublishInvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportAndPublishInv", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.ImportAndPublishInvRequestBody Body;
        
        public ImportAndPublishInvRequest()
        {
        }
        
        public ImportAndPublishInvRequest(VnptPublishService.ImportAndPublishInvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportAndPublishInvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int convert;
        
        public ImportAndPublishInvRequestBody()
        {
        }
        
        public ImportAndPublishInvRequestBody(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial, int convert)
        {
            this.Account = Account;
            this.ACpass = ACpass;
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportAndPublishInvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportAndPublishInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.ImportAndPublishInvResponseBody Body;
        
        public ImportAndPublishInvResponse()
        {
        }
        
        public ImportAndPublishInvResponse(VnptPublishService.ImportAndPublishInvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportAndPublishInvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportAndPublishInvResult;
        
        public ImportAndPublishInvResponseBody()
        {
        }
        
        public ImportAndPublishInvResponseBody(string ImportAndPublishInvResult)
        {
            this.ImportAndPublishInvResult = ImportAndPublishInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInv", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.ImportInvRequestBody Body;
        
        public ImportInvRequest()
        {
        }
        
        public ImportInvRequest(VnptPublishService.ImportInvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int convert;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tkTao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string serial;
        
        public ImportInvRequestBody()
        {
        }
        
        public ImportInvRequestBody(string xmlInvData, string username, string password, int convert, string tkTao, string pattern, string serial)
        {
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.convert = convert;
            this.tkTao = tkTao;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.ImportInvResponseBody Body;
        
        public ImportInvResponse()
        {
        }
        
        public ImportInvResponse(VnptPublishService.ImportInvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportInvResult;
        
        public ImportInvResponseBody()
        {
        }
        
        public ImportInvResponseBody(string ImportInvResult)
        {
            this.ImportInvResult = ImportInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInv", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.publishInvRequestBody Body;
        
        public publishInvRequest()
        {
        }
        
        public publishInvRequest(VnptPublishService.publishInvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VnptPublishService.ArrayOfInt invIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string serial;
        
        public publishInvRequestBody()
        {
        }
        
        public publishInvRequestBody(VnptPublishService.ArrayOfInt invIDs, string username, string password, string pattern, string serial)
        {
            this.invIDs = invIDs;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.publishInvResponseBody Body;
        
        public publishInvResponse()
        {
        }
        
        public publishInvResponse(VnptPublishService.publishInvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publishInvResult;
        
        public publishInvResponseBody()
        {
        }
        
        public publishInvResponseBody(string publishInvResult)
        {
            this.publishInvResult = publishInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvByFkeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvByFkey", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.publishInvByFkeyRequestBody Body;
        
        public publishInvByFkeyRequest()
        {
        }
        
        public publishInvByFkeyRequest(VnptPublishService.publishInvByFkeyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvByFkeyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VnptPublishService.ArrayOfString invFkeys;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string serial;
        
        public publishInvByFkeyRequestBody()
        {
        }
        
        public publishInvByFkeyRequestBody(VnptPublishService.ArrayOfString invFkeys, string username, string password, string pattern, string serial)
        {
            this.invFkeys = invFkeys;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvByFkeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvByFkeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.publishInvByFkeyResponseBody Body;
        
        public publishInvByFkeyResponse()
        {
        }
        
        public publishInvByFkeyResponse(VnptPublishService.publishInvByFkeyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvByFkeyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publishInvByFkeyResult;
        
        public publishInvByFkeyResponseBody()
        {
        }
        
        public publishInvByFkeyResponseBody(string publishInvByFkeyResult)
        {
            this.publishInvByFkeyResult = publishInvByFkeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCus", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.UpdateCusRequestBody Body;
        
        public UpdateCusRequest()
        {
        }
        
        public UpdateCusRequest(VnptPublishService.UpdateCusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XMLCusData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> convert;
        
        public UpdateCusRequestBody()
        {
        }
        
        public UpdateCusRequestBody(string XMLCusData, string username, string pass, System.Nullable<int> convert)
        {
            this.XMLCusData = XMLCusData;
            this.username = username;
            this.pass = pass;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCusResponse", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.UpdateCusResponseBody Body;
        
        public UpdateCusResponse()
        {
        }
        
        public UpdateCusResponse(VnptPublishService.UpdateCusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateCusResult;
        
        public UpdateCusResponseBody()
        {
        }
        
        public UpdateCusResponseBody(int UpdateCusResult)
        {
            this.UpdateCusResult = UpdateCusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCusCertRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCusCert", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.setCusCertRequestBody Body;
        
        public setCusCertRequest()
        {
        }
        
        public setCusCertRequest(VnptPublishService.setCusCertRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCusCertRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string certSerial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string certString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cusCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        public setCusCertRequestBody()
        {
        }
        
        public setCusCertRequestBody(string certSerial, string certString, string cusCode, string username, string pass)
        {
            this.certSerial = certSerial;
            this.certString = certString;
            this.cusCode = cusCode;
            this.username = username;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCusCertResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCusCertResponse", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.setCusCertResponseBody Body;
        
        public setCusCertResponse()
        {
        }
        
        public setCusCertResponse(VnptPublishService.setCusCertResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCusCertResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int setCusCertResult;
        
        public setCusCertResponseBody()
        {
        }
        
        public setCusCertResponseBody(int setCusCertResult)
        {
            this.setCusCertResult = setCusCertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHashInvWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHashInvWithToken", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.getHashInvWithTokenRequestBody Body;
        
        public getHashInvWithTokenRequest()
        {
        }
        
        public getHashInvWithTokenRequest(VnptPublishService.getHashInvWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHashInvWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string serialCert;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string invToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int convert;
        
        public getHashInvWithTokenRequestBody()
        {
        }
        
        public getHashInvWithTokenRequestBody(string Account, string ACpass, string xmlInvData, string username, string password, string serialCert, int type, string invToken, string pattern, string serial, int convert)
        {
            this.Account = Account;
            this.ACpass = ACpass;
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.serialCert = serialCert;
            this.type = type;
            this.invToken = invToken;
            this.pattern = pattern;
            this.serial = serial;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHashInvWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHashInvWithTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.getHashInvWithTokenResponseBody Body;
        
        public getHashInvWithTokenResponse()
        {
        }
        
        public getHashInvWithTokenResponse(VnptPublishService.getHashInvWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHashInvWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getHashInvWithTokenResult;
        
        public getHashInvWithTokenResponseBody()
        {
        }
        
        public getHashInvWithTokenResponseBody(string getHashInvWithTokenResult)
        {
            this.getHashInvWithTokenResult = getHashInvWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvWithToken", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.publishInvWithTokenRequestBody Body;
        
        public publishInvWithTokenRequest()
        {
        }
        
        public publishInvWithTokenRequest(VnptPublishService.publishInvWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string serial;
        
        public publishInvWithTokenRequestBody()
        {
        }
        
        public publishInvWithTokenRequestBody(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial)
        {
            this.Account = Account;
            this.ACpass = ACpass;
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvWithTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.publishInvWithTokenResponseBody Body;
        
        public publishInvWithTokenResponse()
        {
        }
        
        public publishInvWithTokenResponse(VnptPublishService.publishInvWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publishInvWithTokenResult;
        
        public publishInvWithTokenResponseBody()
        {
        }
        
        public publishInvWithTokenResponseBody(string publishInvWithTokenResult)
        {
            this.publishInvWithTokenResult = publishInvWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPublishRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPublish", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.getPublishRequestBody Body;
        
        public getPublishRequest()
        {
        }
        
        public getPublishRequest(VnptPublishService.getPublishRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPublishRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getPublishRequestBody()
        {
        }
        
        public getPublishRequestBody(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPublishResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPublishResponse", Namespace="http://tempuri.org/", Order=0)]
        public VnptPublishService.getPublishResponseBody Body;
        
        public getPublishResponse()
        {
        }
        
        public getPublishResponse(VnptPublishService.getPublishResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPublishResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPublishResult;
        
        public getPublishResponseBody()
        {
        }
        
        public getPublishResponseBody(string getPublishResult)
        {
            this.getPublishResult = getPublishResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface PublishServiceSoapChannel : VnptPublishService.PublishServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PublishServiceSoapClient : System.ServiceModel.ClientBase<VnptPublishService.PublishServiceSoap>, VnptPublishService.PublishServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PublishServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PublishServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), PublishServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PublishServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PublishServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PublishServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PublishServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PublishServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VnptPublishService.ImportAndPublishInvResponse> VnptPublishService.PublishServiceSoap.ImportAndPublishInvAsync(VnptPublishService.ImportAndPublishInvRequest request)
        {
            return base.Channel.ImportAndPublishInvAsync(request);
        }
        
        public System.Threading.Tasks.Task<VnptPublishService.ImportAndPublishInvResponse> ImportAndPublishInvAsync(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial, int convert)
        {
            VnptPublishService.ImportAndPublishInvRequest inValue = new VnptPublishService.ImportAndPublishInvRequest();
            inValue.Body = new VnptPublishService.ImportAndPublishInvRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            return ((VnptPublishService.PublishServiceSoap)(this)).ImportAndPublishInvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VnptPublishService.ImportInvResponse> VnptPublishService.PublishServiceSoap.ImportInvAsync(VnptPublishService.ImportInvRequest request)
        {
            return base.Channel.ImportInvAsync(request);
        }
        
        public System.Threading.Tasks.Task<VnptPublishService.ImportInvResponse> ImportInvAsync(string xmlInvData, string username, string password, int convert, string tkTao, string pattern, string serial)
        {
            VnptPublishService.ImportInvRequest inValue = new VnptPublishService.ImportInvRequest();
            inValue.Body = new VnptPublishService.ImportInvRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.convert = convert;
            inValue.Body.tkTao = tkTao;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            return ((VnptPublishService.PublishServiceSoap)(this)).ImportInvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VnptPublishService.publishInvResponse> VnptPublishService.PublishServiceSoap.publishInvAsync(VnptPublishService.publishInvRequest request)
        {
            return base.Channel.publishInvAsync(request);
        }
        
        public System.Threading.Tasks.Task<VnptPublishService.publishInvResponse> publishInvAsync(VnptPublishService.ArrayOfInt invIDs, string username, string password, string pattern, string serial)
        {
            VnptPublishService.publishInvRequest inValue = new VnptPublishService.publishInvRequest();
            inValue.Body = new VnptPublishService.publishInvRequestBody();
            inValue.Body.invIDs = invIDs;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            return ((VnptPublishService.PublishServiceSoap)(this)).publishInvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VnptPublishService.publishInvByFkeyResponse> VnptPublishService.PublishServiceSoap.publishInvByFkeyAsync(VnptPublishService.publishInvByFkeyRequest request)
        {
            return base.Channel.publishInvByFkeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<VnptPublishService.publishInvByFkeyResponse> publishInvByFkeyAsync(VnptPublishService.ArrayOfString invFkeys, string username, string password, string pattern, string serial)
        {
            VnptPublishService.publishInvByFkeyRequest inValue = new VnptPublishService.publishInvByFkeyRequest();
            inValue.Body = new VnptPublishService.publishInvByFkeyRequestBody();
            inValue.Body.invFkeys = invFkeys;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            return ((VnptPublishService.PublishServiceSoap)(this)).publishInvByFkeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VnptPublishService.UpdateCusResponse> VnptPublishService.PublishServiceSoap.UpdateCusAsync(VnptPublishService.UpdateCusRequest request)
        {
            return base.Channel.UpdateCusAsync(request);
        }
        
        public System.Threading.Tasks.Task<VnptPublishService.UpdateCusResponse> UpdateCusAsync(string XMLCusData, string username, string pass, System.Nullable<int> convert)
        {
            VnptPublishService.UpdateCusRequest inValue = new VnptPublishService.UpdateCusRequest();
            inValue.Body = new VnptPublishService.UpdateCusRequestBody();
            inValue.Body.XMLCusData = XMLCusData;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.convert = convert;
            return ((VnptPublishService.PublishServiceSoap)(this)).UpdateCusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VnptPublishService.setCusCertResponse> VnptPublishService.PublishServiceSoap.setCusCertAsync(VnptPublishService.setCusCertRequest request)
        {
            return base.Channel.setCusCertAsync(request);
        }
        
        public System.Threading.Tasks.Task<VnptPublishService.setCusCertResponse> setCusCertAsync(string certSerial, string certString, string cusCode, string username, string pass)
        {
            VnptPublishService.setCusCertRequest inValue = new VnptPublishService.setCusCertRequest();
            inValue.Body = new VnptPublishService.setCusCertRequestBody();
            inValue.Body.certSerial = certSerial;
            inValue.Body.certString = certString;
            inValue.Body.cusCode = cusCode;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            return ((VnptPublishService.PublishServiceSoap)(this)).setCusCertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VnptPublishService.getHashInvWithTokenResponse> VnptPublishService.PublishServiceSoap.getHashInvWithTokenAsync(VnptPublishService.getHashInvWithTokenRequest request)
        {
            return base.Channel.getHashInvWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<VnptPublishService.getHashInvWithTokenResponse> getHashInvWithTokenAsync(string Account, string ACpass, string xmlInvData, string username, string password, string serialCert, int type, string invToken, string pattern, string serial, int convert)
        {
            VnptPublishService.getHashInvWithTokenRequest inValue = new VnptPublishService.getHashInvWithTokenRequest();
            inValue.Body = new VnptPublishService.getHashInvWithTokenRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.serialCert = serialCert;
            inValue.Body.type = type;
            inValue.Body.invToken = invToken;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            return ((VnptPublishService.PublishServiceSoap)(this)).getHashInvWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VnptPublishService.publishInvWithTokenResponse> VnptPublishService.PublishServiceSoap.publishInvWithTokenAsync(VnptPublishService.publishInvWithTokenRequest request)
        {
            return base.Channel.publishInvWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<VnptPublishService.publishInvWithTokenResponse> publishInvWithTokenAsync(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial)
        {
            VnptPublishService.publishInvWithTokenRequest inValue = new VnptPublishService.publishInvWithTokenRequest();
            inValue.Body = new VnptPublishService.publishInvWithTokenRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            return ((VnptPublishService.PublishServiceSoap)(this)).publishInvWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VnptPublishService.getPublishResponse> VnptPublishService.PublishServiceSoap.getPublishAsync(VnptPublishService.getPublishRequest request)
        {
            return base.Channel.getPublishAsync(request);
        }
        
        public System.Threading.Tasks.Task<VnptPublishService.getPublishResponse> getPublishAsync(string userName, string password)
        {
            VnptPublishService.getPublishRequest inValue = new VnptPublishService.getPublishRequest();
            inValue.Body = new VnptPublishService.getPublishRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((VnptPublishService.PublishServiceSoap)(this)).getPublishAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PublishServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PublishServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PublishServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ubndluankheadmin.vnpt-invoice.com.vn/PublishService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PublishServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ubndluankheadmin.vnpt-invoice.com.vn/PublishService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PublishServiceSoap,
            
            PublishServiceSoap12,
        }
    }
}
